export const CHARACTERS = [
  { id: "mario", name: "Mario", icon: "/characters/mario.png" },
  { id: "luigi", name: "Luigi", icon: "/characters/luigi.png" },
  { id: "dr-mario", name: "Dr. Mario", icon: "/characters/drmario.png" },
  { id: "peach", name: "Peach", icon: "/characters/peach.png" },
  { id: "bowser", name: "Bowser", icon: "/characters/bowser.png" },
  { id: "donkey-kong", name: "Donkey Kong", icon: "/characters/dk.png" },
  { id: "link", name: "Link", icon: "/characters/link.png" },
  { id: "young-link", name: "Young Link", icon: "/characters/younglink.png" },
  { id: "zelda", name: "Zelda", icon: "/characters/zelda.png" },
  { id: "ganondorf", name: "Ganondorf", icon: "/characters/ganondorf.png" },
  { id: "samus", name: "Samus", icon: "/characters/samus.png" },
  { id: "kirby", name: "Kirby", icon: "/characters/kirby.png" },
  { id: "fox", name: "Fox", icon: "/characters/fox.png" },
  { id: "falco", name: "Falco", icon: "/characters/falco.png" },
  { id: "ness", name: "Ness", icon: "/characters/ness.png" },
  { id: "ice-climbers", name: "Ice Climbers", icon: "/characters/climbers.png" },
  { id: "jigglypuff", name: "Jigglypuff", icon: "/characters/puff.png" },
  { id: "pikachu", name: "Pikachu", icon: "h/characters/pikachu.png" },
  { id: "pichu", name: "Pichu", icon: "/characters/pichu.png" },
  { id: "mewtwo", name: "Mewtwo", icon: "/characters/mewtwo.png" },
  { id: "captain-falcon", name: "Captain Falcon", icon: "/characters/falcon.png" },
  { id: "marth", name: "Marth", icon: "/characters/marth.png" },
  { id: "roy", name: "Roy", icon: "/characters/roy.png" },
  { id: "yoshi", name: "Yoshi", icon: "/characters/yoshi.png" },
  { id: "mr-game-watch", name: "Mr. G&W", icon: "/characters/watch.png" },
];
